### ISSUE TITLE
Import area files

### ISSUE THREAD

**Issue by Gwyrdain** [Gwyrdain/apprentices-workshop#65]
## Roadmap
**File**
- [x] Load file and read as text
- [x] Add area revisioning.
- [x] Parse file into header groups

**Header**
- [x] Parse Version 1 headers
- [x] Parse Version 2 headers
- [x] Read numeric flags as hex and piped hex
- [x] Load into database
- [x] Determine and load area number. (Use a room area number/field D?)

**Helps**
- [x] Parse records
- [x] Load into database

**Mobiles**
- [x] Parse records
- [x] Parse flags
- [x] Load into database

**Objects**
- [x] Parse records
- [x] Parse applies (seperate table)
- [x] Parse extra descriptions (seperate table)
- [x] Parse flags
- [x] Load objects into database
- [x] Load applies into database
- [x] Load extra descriptions into database

**Rooms**
- [x] Parse records
- [x] Parse extra descriptions (seperate table)
- [x] Parse exits (seperate table)
- [x] Load rooms into database
- [x] Load extra descriptions into database
- [x] Load exits into database

**Strings**
- [x] Parse records
- [x] Load into database

**Resets**
- [x] Parse records
- [x] Deal with dependencies
- [x] Load into database

**Shops**
- [x] Parse records
- [x] Load into database (dependent to mobiles)

**Specials**
- [x] Parse records
- [x] Load into database (dependent to mobiles)
- [x] Extended specials need to be dealt with one-by-one (except spec_call_for_help and spec_timed_teleport)

**Rspecs**
- [x] Parse records
- [x] Load into database (dependent to rooms)
- [x] Extended specials need to be dealt with one-by-one

**Triggers**
- [x] Parse records
- [x] Load into database (dependent to exits)
- [x] Extended specials need to be dealt with one-by-one

**Misc**
- [x] I reset and deep nesting.
- [x] >100 vnum areas (determine such, and update math for local vnums)

**Comment by Gwyrdain** [comment]
**_For testing only,_** an import button is now available in the areas index page.  It will not load an area file into the database, but it will try to parse an area file and give a rudimentary demonstration that elements of the area file were read properly.  See the above road map and check boxes for what elements you should _expect_ to be parsed.

I'm testing as I go against Nati's farm sample area and some sample area files that were generated out of AW.  It would be good to have some other samples checked -- simply to be sure you don't get a "something went wrong" error page.  (Back checking that all the details are correct can probably wait since the best/easiest way to do so would be to load the file into AW have AW export a file and do a text compare.)

**Comment by TokugawaTFC** [comment]
Once the development environment is available I can bring over some more area files to test this with.

**Comment by Gwyrdain** [comment]
Nati's Farm contains an empty room extra description in Room 30900, that was giving me grief.  Probably should be removed?
https://wiki.tfcmud.com/index.php/Area_File_Sample

**Comment by Gwyrdain** [comment]
Nati's Farm Room 30909 states "Room flags are piped not combined."  This is not in the writers guide.  AW exports will continue to use combined values (I haven't heard that these don't work).

**Comment by TokugawaTFC** [comment]
Combined values do work obviously. Older area files use them. 

An example from your test area is below.

#1500
halfling merchant~
a rotund halfling merchant~
A rotund halfing merchant calls out to you in a jolly tone.
~
This fine fellow has wares aplenty to sell you.
Step right up and have a look -- you'll not be disappointed.
~
**2|64** 16777216 0 S
1 0 0 0d0+0 0d0+0
0 0
8 8 0
L
17 16

**Comment by TokugawaTFC** [comment]
Note the bolded numeric piped values. This is how the piped values work for mob act flags, object extra flags and room flags.

**Comment by Gwyrdain** [comment]
Ok, I will have to go back and make sure that basically all of those (bitwise) flags can be read either way.

**Comment by TokugawaTFC** [comment]
I hope that was all of the flags. I think it was.

**Comment by Gwyrdain** [comment]
Now that my memory was jogged, I think I remember something about area flags being piped too.  Here is the list I have:
*area flags
*mob act flags
*mob affect flags
*obj extra flags
*obj wear flags
*container flags (probably never used piped since this is in the v1 object position)
*room flags

The way I have it reading these values, it doesn't hurt to cover all these bases.

**Comment by TokugawaTFC** [comment]
Sounds good to me. :)

**Comment by Gwyrdain** [comment]
Unless you're specifically watching the progress bar on this on or checking back in you may be missing the roadmap edits and checkoffs.  So a quick update:  At this time all blocks are loading to the database seemingly well up through strings.  Just resets, shops, both specs, and triggers to go.

**Comment by Gwyrdain** [comment]
Area specials complete. Only nested resets (I, etc.) and extended specials need further work.

**Comment by Cordir** [comment]
i've done two test uploads of different areas, and have not gotten any error messages, FYI. But neither zone had Particular Weirdnesses to them. (e.g. undocumented reset types, etc., that it shouldn't be expected to know how to deal with.)

**Comment by Cordir** [comment]
Do you get debug / error info when we try to upload a file?

**Comment by TokugawaTFC** [comment]
I've tried to import two area files. The biggest I could find and then midgaard. Both failed with a generic message saying something went wrong.

Could we get some detailed messages to help with debugging the failure?

**Comment by Cordir** [comment]
Kharad Delving loaded okay.
Tier Sh'Halen errored. Cordir's Lesser goddess temple errored.

Could it be a line length issue? (HA! Gimme back my 80 characters, damnit! :P )

**Comment by Gwyrdain** [comment]
I have enabled verbose errors in the production environment.  At the moment you're still only able to do the parsing bit, but this debugging will be very helpful (possibly also painful).

**Comment by Cordir** [comment]
So... what can we do to help test/break stuff, to make issues easier for you to see? What kind of info do you need?

**Comment by Gwyrdain** [comment]
Send the the blank file and I will either fix what's causing that error tell you what's wrong with the file.  Otherwise, we should probably take the errors one at a time, as follows:
1. Find an import that doesn't work
2. Report the verbose error
3. Go back and forth to try to narrow down what's up.
(Alternately, it would be much easier and faster in terms in terms of the trial and error process if I had the file in question, so if someone wants to get to work on that special dispensation and NDA...)

**Comment by Cordir** [comment]
I've sent Gwyrdain my temple, the empty file, and HOM I. 
I trust him. :)

**Comment by Gwyrdain** [comment]
80 characters will not be an import issue, however, it will screw things up on re-export since AW will try to wrap characters at 75.  If areas have been approved at 80 in the past can that "requirement" just be abrogated?

**Comment by TokugawaTFC** [comment]
No, we cannot get rid of the 80 character requirement. We have existing zones that go  past 75 characters. If we were to import the file it would mess up the formatting. Can you make it so it word wraps at 81 characters? Then the max width could be 80.

**Comment by Gwyrdain** [comment]
Sorry, I meant bump the 75 (from the AWG) up to 80.

Yes, if I set the word wrap to 80 it will produce lines of up to but not more than 80.

**Comment by TokugawaTFC** [comment]
The area writers guide is talking about style guidelines to make rooms, mobs and objects appear ok. Rooms should be no more than 75, mobs and objects should be no more than 70. 80 is ok for all of them for an import maximum length.

**Comment by Gwyrdain** [comment]
A number of parsing errors were found and resolved.  Please continue testing as you are able.

**Comment by Gwyrdain** [comment]
Updated 80 as hard maximum.

**Comment by TokugawaTFC** [comment]
I was able to import kharad.are without errors. midgaard.are is still giving me issues as well as hallofmemory.are.

**Comment by Gwyrdain** [comment]
Email MG error page, please.

**Comment by TokugawaTFC** [comment]
Emailed the error to you.

Hall of Memory also fails but you have that file so should be able to debug it easier than me emailing more info.

**Comment by Cordir** [comment]
I sent him hallofmemory-c.are  -- is that what you're uploading?

**Comment by TokugawaTFC** [comment]
Nope. I am upload the live version of the file.

**Comment by Cordir** [comment]
(gwyrdain: Hall of memory was so big sirak's muditor couldn't process it. so a lot of it was built by hand. some of it was a bit messy.)

Toku:  On the hallofmemory-c.are file, there was apparently duplicate exit references on two lines. When I deleted those, the file imports.  (lines 2443 & 2444 / 2481 & 2482)  Could you see if those exits are duplicated in your live file, and if so, once corrected, see if it uploads?

**Comment by Cordir** [comment]
(though, it doesn't look like it brought in the whole file...?) it's only displaying up through room #32627.

**Comment by TokugawaTFC** [comment]
I do not see the same data on the line numbers you cited.

**Comment by Cordir** [comment]
Maybe it was already cleaned up on your end?
Room 32601 / A Wide Corridor of Gleaming Marble - duplicate exit D3

**Comment by Cordir** [comment]
Which means something else is making yours fail.

**Comment by TokugawaTFC** [comment]
Heh, apparently that does not cause the mud to crash. I did have that duplication. What was the other room vnum? I'll check for the other one as well.

**Comment by TokugawaTFC** [comment]
Found the other one. 32602. Exit D2.

**Comment by TokugawaTFC** [comment]
After removing the duplicated exits I was able to import the file. Though as you saw it only imported to room 32627.

**Comment by Gwyrdain** [comment]
Regarding Midgaard, we were expecting the bracing in the ver 1 area header, as shown below.  Based on seeing MG w/o braces, I assume there are other areas with this syntax so I will do an update that allows either syntax.

![image](https://cloud.githubusercontent.com/assets/7820937/14832632/02b01512-0bb0-11e6-9118-7a5dbb0d913e.png)

**Comment by Gwyrdain** [comment]
Updated now.  Try again when time permits.

**Comment by Gwyrdain** [comment]
The missing rooms > 32627 in HOM should show now.  It was a display error rather than a parsing error, where the "<" and ">" characters needed to be translated into web safe "&lt" and "&gt" to not goof up the display.

**Comment by Gwyrdain** [comment]
Lots of good fixes made today.  I have opened up real importing on the live environment.  As noted on the roadmap I would expect wonky results with the I reset for now and some extended specials will generate errors.  Check it out.

**Comment by Cordir** [comment]
This, my friend..
![image](https://cloud.githubusercontent.com/assets/10890489/14859087/37d87ad2-0c68-11e6-805f-1c32bbcef562.png)
is a thing of beauty and awesomeness.

**Comment by Gwyrdain** [comment]
Added rudimentary support for C and F resets -- will import and export "as is" values.  Editing and commenting is not possible without syntax definition.

**Comment by TokugawaTFC** [comment]
What are C and F resets?

**Comment by Gwyrdain** [comment]
C is give a random item and F is equip a random item as best as I can guess/interpolate.

**Comment by TokugawaTFC** [comment]
Ah yes. Those are not documented. hm

**Comment by Gwyrdain** [comment]
Additionally, the examples I saw appear to be in conflict with one another...

**Comment by TokugawaTFC** [comment]
Can we create a new post for the discussion of these? I can find examples
in areas if that will help.

**Comment by Gwyrdain** [comment]
Yes, see Issue #94.

**Comment by Gwyrdain** [comment]
At this time the nested I & P resets and the extended area specials seem to be importing correctly.  This completes the roadmap and I'm excited to get this issue closed.  Keep a close eye on imports and be sure to compare result to the prior file.  Please open new issues as you find problems.
